version: "3.7"
services:
  app:
    build:
      args:
        user: tefzon
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: tefzon
    container_name: tefzon-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - tefzon

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: tefzon-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - tefzon
  pma:
    image: phpmyadmin:5.1
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=${DB_HOST}
        - PMA_USER=${DB_USERNAME}
        - PMA_PASSWORD=${DB_PASSWORD}
        - PMA_PORT=${DB_PORT}
    depends_on:
        - db
    ports:
        - 8888:80

  nginx:
    image: nginx:latest
    container_name: tefzon-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - tefzon

networks:
  tefzon:
    external: true
    driver: bridge